[package]
name = "rust"
version = "0.1.0"
authors = ["Rob Jenks <robjenks@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.9.0"
scan_fmt = "0.2.5"
enum_primitive = "0.1.1"
num-traits = "0.2.14"