[package]
name = "rust"
version = "0.1.0"
authors = ["Rob Jenks <robjenks@gmail.com>"]
edition = "2021"

[dependencies]
itertools = "0.12.0"
regex = "1.10.2"
once_cell = "1.18.0"
scan_fmt = "0.2.6"
mut-binary-heap = "0.1.0"
